---
name: Ansible Release
'on':
  workflow_call:
    secrets:
      GALAXY_TOKEN:
        description: 'The token to publish to ansible-galaxy'
        required: true

jobs:
  release:
    name: Ansible Release
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: version.sh
          path: metadata

      - name: Source metadata
        id: metadata
        run: |
          source metadata/version.sh
          echo "project_name=${PROJECT_NAME}" >> $GITHUB_ENV
          echo "role_name=$(echo ${PROJECT_NAME} | rev | cut -d '-' -f1 | rev)" >> $GITHUB_ENV
          echo "project_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: |
          echo "ansible-galaxy role import --api-key ${{ secrets.GALAXY_TOKEN }} --role-name ${{ env.role_name }} ${{ env.project_owner }} ${{ env.project_name }}"
          if [ $GITHUB_REF_NAME = main ]; then
            ansible-galaxy role import --api-key ${{ secrets.GALAXY_TOKEN }} --role-name ${{ env.role_name}} ${{ env.project_owner }} ${{ env.project_name }}
          fi
