---
name: Ansible Molecule Test
'on':
  workflow_call:

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'grababyte/centos-base:0.2.0' # 8.4
          - 'grababyte/ubuntu-base:0.2.0' # 2204
          - 'grababyte/alpine-base:0.7.1' # 3.14

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Molecule dependencies
        run: pip3 install ansible molecule[docker] docker

      - name: Run Molecule tests
        run: molecule --debug test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_IMAGE: ${{ matrix.image }}
