---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  yaml-lint:
    uses: ./.github/workflows/yamlLint.yml
    with:
      yamlPath: '.github'
    needs: get-version
  sonar-scan:
    uses: ./.github/workflows/sonarScan.yml
    secrets:
      WORKFLOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs: [yaml-lint]
  semantic-release:
    uses: GrabAByte/github-devops-workflows/.github/workflows/semanticRelease.yml@0.14.0
    needs: [yaml-lint, sonar-scan]
