---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

env:
  METADATA_FILE: 'metadata.json'

jobs:
  get-version:
    uses: ./.github/workflows/getVersion.yml
    with:
      metadataFile: ${{ env.METADATA_FILE }}
      metadataPath: .
  yaml-lint:
    uses: ./.github/workflows/yamlLint.yml
    with:
      yamlPath: '.github'
    needs: get-version
  update-version:
    uses: ./.github/workflows/updateVersion.yml
    with:
      gitUsername: 'grababyte'
      gitEmail: 'grababyte@github.com'
      metadataFile: ${{ env.METADATA_FILE }}
      metadataPath: .
    needs: yaml-lint
