---
name: Docker Build
'on':
  workflow_call:
    inputs:
      dockerfilePath:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Build Code
        run: |
          docker build -t="test" -f ${{ inputs.dockerfilePath }} .
