---
name: Docker Build and Publish
'on':
  workflow_call:
    inputs:
      dockerfilePath:
        required: true
        type: string
    secrets:
      username:
        description: 'The Docker Hub Username'
        required: true
      token:
        description: 'The Docker Hub Password'
        required: true

jobs:
  docker-build-publish:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Download file
        uses: actions/download-artifact@v1
        with:
          name: metadata.sh
          path: metadata

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build Docker Image
        run: |
          source metadata/metadata.sh
          docker build -t="${GITHUB_REPOSITORY_OWNER,,}/$projectName:$projectVersion" -f ${{ inputs.dockerfilePath }} .

      - name: Publish Docker Image
        run: |
          source metadata/metadata.sh
          docker push ${GITHUB_REPOSITORY_OWNER,,}/$projectName:$projectVersion
