---
name: Docker Build and Publish
'on':
  workflow_call:
    inputs:
      dockerfilePath:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: 'The Docker Hub Username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'The Docker Hub Password'
        required: true

jobs:
  docker-build-publish:
    name: Build and Publish Image
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Download file
        uses: actions/download-artifact@v1
        with:
          name: version.sh
          path: metadata

      - name: Source metadata
        id: metadata
        run: |
          source metadata/version.sh
          echo "::set-output name=NAME::${PROJECT_NAME}"
          echo "::set-output name=VERSION::${FUTURE_VERSION}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.dockerfilePath }}
          push: ${{ contains(github.ref, 'refs/heads/main') }}
          tags: ${{ github.repository_owner }}/${{ steps.metadata.outputs.NAME }}:${{ steps.metadata.outputs.VERSION }}
