---
name: Dockerfile Linter
'on':
  workflow_call:
    inputs:
      dockerfilePath:
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        run: |
          docker run --rm -i -v ${PWD}/.hadolint.yml:/.hadolint.yml hadolint/hadolint < ${{ inputs.dockerfilePath }} && \
          echo "Docker Linting: Successful"
