---
name: Docker Vulnerability Scan
'on':
  workflow_call:
    inputs:
      dockerfilePath:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: 'The Docker Hub Username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'The Docker Hub Password'
        required: true
      SNYK_TOKEN:
        description: 'The Snyk API Token'
        required: true

jobs:
  scan:
    name: Scan
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Download file
        uses: actions/download-artifact@v1
        with:
          name: version.sh
          path: metadata

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Source Metadata
        id: metadata
        run: |
          source metadata/version.sh
          echo "::set-output name=NAME::${PROJECT_NAME}"
          echo "::set-output name=VERSION::${FUTURE_VERSION}"

      - name: Docker Build
        uses: docker/build-push-action@v2
          with:
          context: .
          file: ${{ env.dockerfilePath }}
          push: ${{ contains(github.ref, 'refs/heads/main') }}
          tags: ${GITHUB_REPOSITORY_OWNER,,}/${{ steps.metadata.outputs.PROJECT_NAME}}:${{ steps.metadata.outputs.FUTURE_VERSION }}

      - name: Run Snyk Vulnerability scanner for Docker
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${GITHUB_REPOSITORY_OWNER,,}/${{ steps.metadata.outputs.NAME }}:${{ steps.metadata.outputs.VERSION }}
          args: --file=${{ inputs.dockerfilePath }}
