---
name: Docker Build
'on':
  workflow_call:
    inputs:
      dockerfilePath:
        required: true
        type: string
      outputFile:
        required: true
        type: string
      outputPath:
        required: true
        type: string

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Download file
        uses: actions/download-artifact@v1
        with:
          name: ${{ inputs.outputFile }}
          path: ${{ inputs.outputPath }}

      - name: Build Image
        run: |
          source ${{ inputs.outputPath }}/${{ inputs.outputFile }}
          docker build -t="$GITHUB_REPOSITORY_OWNER/$projectName:$projectVersion" -f ${{ inputs.dockerfilePath }} .
