---
name: Docker Build and Publish
'on':
  workflow_call:
    inputs:
      dockerfilePath:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: 'The Docker Hub Username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'The Docker Hub Password'
        required: true

jobs:
  docker-build-publish:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Download file
        uses: actions/download-artifact@v1
        with:
          name: metadata.sh
          path: metadata

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          source metadata/metadata.sh
          docker build -t="${GITHUB_REPOSITORY_OWNER,,}/${PROJECT_NAME}:${CURRENT_VERSION}" -f ${{ inputs.dockerfilePath }} .

      - name: Publish Docker Image
        run: |
          source metadata/metadata.sh
          docker push ${GITHUB_REPOSITORY_OWNER,,}/${PROJECT_NAME}:${CURRENT_VERSION}
