---
name: Docker Build
'on':
  workflow_call:
    inputs:
      dockerfilePath:
        required: true
        type: string

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Download file
        uses: actions/download-artifact@v1
        with:
          name: metadata.sh
          path: metadata

      - name: Build Image
        run: |
          source metadata/metadata.sh
          docker build -t="${GITHUB_REPOSITORY_OWNER,,}/$projectName:$projectVersion" -f ${{ inputs.dockerfilePath }} .
