---
name: Dockerfile Scan
'on':
  workflow_call:
    inputs:
      dockerfilePath:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: 'The Docker Hub Username'
        required: true
      DOCKERHUB_TOKEN:
        description: 'The Docker Hub Password'
        required: true
      SNYK_TOKEN:
        description: 'The Snyk API Token'
        required: true

jobs:
  scan:
    name: Scan
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install docker-scan-plugin
        run: |
          sudo apt update -y && \
          sudo apt-get install docker-scan-plugin

      - name: Scan Dockerfile
        run: |
          docker scan --login --token ${{ secrets.SNYK_TOKEN }}
          docker scan --file ${{ inputs.dockerfilePath }} && \
          echo "Docker Security Scan: Successful"
