---
name: Download Artifact
'on':
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  downloadArtifact:
    name: Download Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.path }}
      - name: Source Metadata
        run: |
          source ${{ inputs.path }}
          echo $name
          echo $version
