---
name: Helm Linter
'on':
  workflow_call:
    inputs:
      chartPath:
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Lint Charts
        run: |
          helm lint ${{ inputs.chartPath }} && \
          echo "Helm Linting: Successful"
