---
name: YAML Linter
'on':
  workflow_call:

job:
  metadata:
    name: Upload Metadata
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          if [ ! -d .artifacts ]; then mkdir .artifacts; di
          echo "name=foo" >> .artifacts/metadata.txt
          echo "version=0.0.0" >> .artifacts/metadata.txt
      - name: Upload Metadata File
        uses: actions/upload-artifact@v1
        with:
          name: metadata
          path: metadata.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat homework/math-homework.txt`
          expr $value \* 9 > homework/math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: homework/math-homework.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat homework/math-homework.txt`
          echo The result is $value
