---
name: Python Release
'on':
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true

jobs:
  release:
    name: PIP Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Release PIP package to PYPI
        run: |
          echo "I will perform Python Release"
