---
name: Python Scan
'on':
  workflow_call:
    secrets:
      SNYK_TOKEN:
        description: 'The Snyk API Token'
        required: true

jobs:
  scan:
    name: Python Vulnerability Scan
    environment: CI
    run_on: ubuntu-latest
    steps:
      - name: Check out the codebase
      - uses: actions/checkout@v2

      - name: Run Snyk Vulnerability scanner for Python
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
