---
name: Bash Linter
'on':
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Lint code
        run: |
          for i in $(find . -name "*.sh"); do
            shellcheck "$i"
          done && \
          echo "Bash Linting: Successful"
