---
name: Sonarcloud Scan
'on':
  workflow_call:
    secrets:
      WORKFLOW_GITHUB_TOKEN:
        description: 'The github account Token'
        required: true
      SONAR_TOKEN:
        description: 'The sonarcloud.io API Token'
        required: true

jobs:
  sonarcloud:
    name: Code Analysis
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Source Metadata
        id: metadata
        run: |
          echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Sonar Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Case sensitivity requires OWNER to be passed as lowercase, this will inherantly work for all lowercase users
          args: >
            -Dsonar.organization=${{ env.owner }}
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
            -Dsonar.sources=.
