---
name: Terraform Test
'on':
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      terraformPath:
        required: true
        type: string
      varFile:
        required: true
        type: string
    secrets:
      account:
        required: true
      role:
        required: true

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.account }}:role/${{ secrets.role }}
          aws-region: ${{ inputs.region }}

      - name: Validate Terraform
        run: |
          cd ./${{ inputs.terraformPath }} && \
          terraform init && \
          terraform test -var-file ${{ inputs.varFile }}
