---
name: Terraform Apply
'on':
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      whitepaper:
        required: true
        type: string

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/grababyte
          aws-region: eu-west-1

      - name: Apply Terraform
        run: |
          cd whitepapers/${{ inputs.whitepaper }} && \
          terraform init -backend-config=backends/${{ inputs.workspace }} && \
          terraform workspace new ${{ inputs.workspace }} && \
          terraform workspace select ${{ inputs.workspace }} && \
          terraform apply --auto-approve
