---
name: Terraform Apply
'on':
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      terraformPath:
        required: true
        type: string
      terraformVars:
        required: true
        type: string
      region:
        required: true
        type: string
    secrets:
      account:
        required: true
      role:
        required: true

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.account }}:role/${{ secrets.role }}
          aws-region: ${{ inputs.region }}

      - name: Apply Terraform
        run: |
          cd ${{ inputs.terraformPath }} && \
          terraform init && \
          terraform workspace new ${{ inputs.workspace }} || \
          terraform workspace select ${{ inputs.workspace }} && \
          terraform apply --auto-approve -var-file ${{ inputs.terraformVars }}
