---
name: Terraform Plan
'on':
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Plan Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init -backend-config=backends/${{ inputs.workspace }} && \
          terraform workspace new ${{ inputs.workspace }} && \
          terraform workspace select ${{ inputs.workspace }} && \
          terraform plan || :
