---
name: Terraform Plan
'on':
  workflow_call:
    inputs:
      terraformPath:
        required: true
        type: string

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Initialize Terraform
        run: |
          terraform -chdir=environments/${{ inputs.terraformPath }} init

      - name: Plan Terraform
        run: |
          terraform -chdir=environments/${{ inputs.terraformPath }} plan
