---
name: Terraform Linter
'on':
  workflow_call:
    inputs:
      terraformPath:
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Lint Terraform
        run: |
          tflint --chdir=environments/${{ inputs.terraformPath }}
