---
name: Terraform Security Scanner
'on':
  workflow_call:
    inputs:
      terraformPath:
        required: true
        type: string

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          curl -L "$(curl -s https://api.github.com/repos/tfsec/tfsec/releases/latest | grep -o -E "https://.+tfsec-linux-amd64")" -o tfsec && \
          chmod +x tfsec

      - name: Scan Terraform
        run: |
          ./tfsec ${{ inputs.terraformPath }}
