---
name: Terraform Validator
'on':
  workflow_call:
    inputs:
      terraformPath:
        required: true
        type: string

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Validate Terraform
        run: |
          cd ./${{ inputs.terraformPath }} && \
          terraform init && \
          terraform validate
