---
name: Update Version
'on':
  workflow_call:
    inputs:
      gitUsername:
        required: true
        type: string
      gitEmail:
        required: true
        type: string
      metadataFile:
        required: true
        type: string
      metadataPath:
        required: true
        type: string

jobs:
  versioning:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Download Metadata
        uses: actions/download-artifact@v1
        with:
          name: version.sh
          path: metadata

      - name: Bump Versioning and update CHANGELOG.md
        run: |
          source metadata/version.sh
          if [ $GITHUB_REF_NAME = main ]; then
            # Update CHANGELOG.md with appropriate entry
            ## <HERE>
            # Bump Version to required new version
            echo "${CURRENT_VERSION} to ${FUTURE_VERSION} in file ${{ inputs.metadataPath }}/${{ inputs.metadataFile }}"
            sed -i "s/${CURRENT_VERSION}/${FUTURE_VERSION}/" ${{ inputs.metadataPath }}/${{ inputs.metadataFile }}
            # Commit back to mainline with updates, if there are changes
            if [[ ! -z $(git status -s) ]]; then
              git config --global user.name "${{ inputs.gitUsername }}"
              git config --global user.email "${{ inputs.gitEmail }}"
              git add ${{ inputs.metadataPath }}/${{ inputs.metadataFile }}
              git commit -m "github pipeline: automated version bump from ${CURRENT_VERSION} to ${FUTURE_VERSION}"
              git push
            fi
          fi
