---
name: Upload Metadata
'on':
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  metadata:
    name: Gather Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Output metadata to artifact
        run: |
          if [ ! -d ${{ inputs.path }} ]; then
            mkdir ${{ inputs.path }}
          fi
          echo "name=foo" >> ${{ inputs.path }}/${{ inputs.artifact }}
          echo "version=0.0.0" >> ${{ inputs.path }}/${{ inputs.artifact }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.path }}
