---
name: Upload Metadata
'on':
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  metadata:
    name: Gather Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Output metadata to artifact
        run: |
          sed -i 's/0.0.0/0.0.1/' ${{ inputs.path }}/${{ inputs.artifact }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.path }}
          retention-days: 1
