---
name: Version Bump
'on':
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Bump Artifact Version
        run: |
          ## This code block will contain the logic to Bump metadata on CHANGELOG based on the branch naming convention
          sed -i 's/0.0.0/0.0.1/' ${{ inputs.path }}/${{ inputs.artifact }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.path }}
          retention-days: 1
