---
name: YAML Linter
'on':
  workflow_call:
    inputs:
      yamlPath:
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Linting Dependencies
        run: pip3 install yamllint

      - name: Lint code
        run: |
          yamllint ${{ inputs.yamlPath }} && \
          echo "YAML Linting: Successful"
